# Generated by Django 4.1 on 2022-08-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0002_alter_reservation_flight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='departurecity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
